kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mariadb-pv-claim
  namespace: default
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi