apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: default
spec:
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress:4.9.0
        name: wordpress
        ports:
         - containerPort: 80
        volumeMounts:
         - name: wordpress-persistent-storage
           mountPath: /var/www/html
        env:
          # Use secret in real usage
         - name: WORDPRESS_DB_HOST
           value: mariadb:3306
         - name: WORDPRESS_DB_USER
           value: root
         - name: WORDPRESS_DB_PASSWORD
           value: password
         - name: WORDPRESS_DB_NAME
           value: wordpressdb
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-pv-claim
